language: php

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install

script:
  - touch ./storage/database/database.sqlite
  - php artisan cache:clear
  - php artisan migrate --database=sqlite --force
  - mkdir -p build/logs 
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php ./vendor/bin/php-coveralls -v

os:
  - linux

jobs:
  allow_failures:
    - php: 7.4
