version: '2'
services:
  web:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
  app:
    build: ./docker
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
  database:
    image: postgres:9.6.12
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: ucm
    ports:
      - 5432:5432
    volumes:
      - ./storage/data:/var/lib/postgresql/data
      - ./storage/database/create.sql:/docker-entrypoint-initdb.d/create.sql
    links:
      - app
